# Generated by Django 5.2.7 on 2025-10-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyforecast',
            name='pressure',
            field=models.DecimalField(decimal_places=2, help_text='Presión', max_digits=7),
        ),
    ]
