# Generated by Django 5.2.7 on 2025-10-05 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dailyforecast_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyforecast',
            name='CO_surface_conc',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='NO2_concentration',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='O3_concentration',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='SO2_concentration',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='avg_wind_speed_10m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='cloud_area_pred',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='dust_concentration',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='frozen_precip',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='potential_vorticity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='skin_temperature',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='snowfall_pred',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='specific_humidity_pred',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='surface_pressure_pred',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='temperature_surface',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='total_precip_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='clouds',
            field=models.DecimalField(decimal_places=1, help_text='Nubosidad', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='current_temp',
            field=models.DecimalField(decimal_places=1, help_text='Temperatura actual', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='dew_point',
            field=models.DecimalField(decimal_places=1, help_text='Punto de rocío', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='feels_like_temp',
            field=models.DecimalField(decimal_places=1, help_text='Sensación térmica', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='humidity',
            field=models.IntegerField(help_text='Humedad en %'),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='max_temp',
            field=models.DecimalField(decimal_places=1, help_text='Temperatura máxima', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='min_temp',
            field=models.DecimalField(decimal_places=1, help_text='Temperatura mínima', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='precipitation_prob',
            field=models.IntegerField(help_text='Probabilidad de lluvia en %'),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='pressure',
            field=models.DecimalField(decimal_places=2, help_text='Presión Atmosférica', max_digits=7),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='summary',
            field=models.TextField(blank=True, help_text='Resumen del día', null=True),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='sunrise',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='sunset',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='visibility',
            field=models.DecimalField(decimal_places=1, help_text='Visibilidad', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='wind_speed',
            field=models.DecimalField(decimal_places=1, help_text='Velocidad del viento', max_digits=4),
        ),
    ]
